# task file for install_haproxy

- name: Install the latest version of haproxy
  package:
    name: haproxy
    state: present

- name: Configure haproxy
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# BEGIN Configuring haproxy"
    block: |
      frontend k8s
        bind {{k8s_loadbalancer_ip}}:6443
        mode tcp
        default_backend k8s

      backend k8s
        mode tcp
        balance roundrobin
        option tcplog
        option tcp-check
        server {{ k8s_master1 }} {{ k8s_master1_ip }}:6443 check
        server {{ k8s_master2 }} {{ k8s_master2_ip }}:6443 check
        server {{ k8s_master3 }} {{ k8s_master3_ip }}:6443 check

- name: restart service haproxy
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: haproxy

